import Head from 'next/head'
import { getSession } from "next-auth/react"

export const getServerSideProps = async (ctx) => {

  const session = await getSession(ctx)
  


  return {
    props: {
      user: session.user
    }
  }
}

export default function Home({user}) {

  console.log(user);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{user.name}</h1>
      <p>{user.email}</p>
      <img src={user.image} alt="" />
    </div>
  )
}
